modLoader = "javafml"
loaderVersion = "[${forge_min_version},)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.contentsync]]
modId = "forge"
mandatory = true
versionRange = "[${forge_min_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.contentsync]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.contentsync]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_min_version},)"
ordering = "AFTER"
side = "BOTH"